class OrderClosedException(Exception):
    pass


class SelfOrderException(Exception):
    pass